# Generated by Django 4.1 on 2022-08-25 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hermano',
            new_name='Familia',
        ),
        migrations.DeleteModel(
            name='Mama',
        ),
        migrations.DeleteModel(
            name='Papa',
        ),
    ]
