# Generated by Django 4.1 on 2022-08-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0002_rename_hermano_familia_delete_mama_delete_papa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='nacimiento',
        ),
    ]
